services:
  backend:
    user: root
    container_name: backend_vote
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - static:/app/public
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis
      - mysql_db
  
  worker:
  container_name: worker_vote
  build:
    context: .
    dockerfile: Dockerfile
  restart: always
  env_file:
    - .env
  depends_on:
    - redis
    - mysql_db
  command: bun run prod:worker

  redis:
    image: redis:latest
    container_name: redis_vote
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_NAME=${REDIS_NAME}
    ports:
      - 6378:${REDIS_PORT}
    volumes:
      - redis-data:/data

  mysql_db:
    image: mysql:8.0.25
    container_name: mysql_vote
    restart: unless-stopped
    command:
      - --sort_buffer_size=1073741824
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 3305:${DB_PORT}
    volumes:
      - db-backup:/var/lib/mysql

volumes:
  db-backup:
  static:
  redis-data:
