/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MultiContestVotingAbi } from './MultiContestVotingAbi';
export * as factories from './factories';
export { MultiContestVotingAbi__factory } from './factories/MultiContestVotingAbi__factory';
